USE ROLE SNOWFLAKE_LEARNING_ROLE;
USE DATABASE DB_TEAM1;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- suspend fallback and email task first
ALTER TASK DB_TEAM1.BRONZE.TASK_SEND_FAILURE_EMAIL   SUSPEND;
ALTER TASK DB_TEAM1.BRONZE.TASK_FALLBACK_BRONZE_LOAD SUSPEND;

-- new task: fires after fallback, checks if fallback actually loaded data
-- if yes, rebuilds all Silver and Gold tables
CREATE OR REPLACE TASK DB_TEAM1.BRONZE.TASK_FALLBACK_SILVER_GOLD_REFRESH
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
    COMMENT   = 'Refreshes Silver and Gold after fallback load, only if fallback actually ran'
    AFTER DB_TEAM1.BRONZE.TASK_FALLBACK_BRONZE_LOAD
AS
DECLARE
    v_fallback_succeeded INTEGER DEFAULT 0;
BEGIN
    -- check if fallback actually loaded data today (not skipped)
    SELECT COUNT(*) INTO :v_fallback_succeeded
    FROM DB_TEAM1.BRONZE.PIPELINE_LOG
    WHERE RUN_TYPE = 'FALLBACK'
      AND STATUS   = 'SUCCESS'
      AND DATE(RUN_TIMESTAMP) = CURRENT_DATE();

    IF (:v_fallback_succeeded = 0) THEN
        -- fallback skipped today (primary succeeded), nothing to do
        RETURN 'Fallback skipped today, Silver/Gold already current';
    END IF;

    -- fallback actually ran — rebuild Silver and Gold
    -- silver transactions
    CREATE OR REPLACE TABLE DB_TEAM1.SILVER.TRANSACTIONS AS
    SELECT
        CHANNEL_ID, CHANNEL_DESC, TRANSACTION_ID,
        TRY_TO_DATE(TRANSACTION_DATE::STRING)           AS TRANSACTION_DATE,
        TRANSACTION_TYPE,
        LINE_ID::NUMBER                                 AS LINE_ID,
        SKU_ID, STORE_ID_ORIGIN, STORE_ID_FULLFILLED,
        ORDER_FULFILLMENT_METHOD,
        QUANTITY_SOLD::NUMBER                           AS QUANTITY_SOLD,
        CURRENT_MSRP::FLOAT                             AS CURRENT_MSRP,
        UNIT_RETAIL_PRICE::FLOAT                        AS UNIT_RETAIL_PRICE,
        DISCOUNT_AMOUNT::FLOAT                          AS DISCOUNT_AMOUNT,
        UNIT_NET_SELLING_PRICE::FLOAT                   AS UNIT_NET_SELLING_PRICE,
        TOTAL_EXTENDED_LINE_AMOUNT::FLOAT               AS TOTAL_EXTENDED_LINE_AMOUNT,
        UNIT_COST::FLOAT                                AS UNIT_COST,
        TOTAL_COST::FLOAT                               AS TOTAL_COST,
        PRICE_STATUS, CLEARANCE_INDICATOR,
        TRY_TO_DATE(LAUNCH_DATE::STRING)                AS LAUNCH_DATE,
        LAUNCH_PRICE::FLOAT                             AS LAUNCH_PRICE,
        TRY_TO_TIMESTAMP(REPLACE(CREATED_TIMESTAMP, '-', ' '), 'YYYY MM DD HH24.MI.SS.FF6') AS CREATED_TIMESTAMP,
        TRY_TO_TIMESTAMP(REPLACE(UPDATED_TIMESTAMP, '-', ' '), 'YYYY MM DD HH24.MI.SS.FF6') AS UPDATED_TIMESTAMP,
        _SOURCE_FILE, _LOADED_AT,
        CURRENT_TIMESTAMP()                             AS _STAGED_AT,
        CASE WHEN TRANSACTION_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS DQ_TRANSACTION_ID,
        CASE WHEN SKU_ID IS NULL THEN 'FAIL' ELSE 'PASS' END AS DQ_SKU_ID,
        CASE WHEN STORE_ID_ORIGIN IS NULL THEN 'FAIL' ELSE 'PASS' END AS DQ_STORE_ID,
        CASE WHEN QUANTITY_SOLD IS NULL OR QUANTITY_SOLD::NUMBER < 0 THEN 'FAIL' ELSE 'PASS' END AS DQ_QUANTITY,
        CASE WHEN TOTAL_EXTENDED_LINE_AMOUNT IS NULL OR TOTAL_EXTENDED_LINE_AMOUNT::FLOAT < 0 THEN 'FAIL' ELSE 'PASS' END AS DQ_AMOUNT
    FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID, LINE_ID ORDER BY _LOADED_AT DESC) AS RN
        FROM DB_TEAM1.BRONZE.TRANSACTIONS
    ) WHERE RN = 1;

    -- silver inventory
    CREATE OR REPLACE TABLE DB_TEAM1.SILVER.INVENTORY AS
    SELECT
        CHANNEL_ID, CHANNEL_DESC, SKU_ID,
        STORE_ID::NUMBER                    AS STORE_ID,
        TRY_TO_DATE(INVENTORY_DATE::STRING) AS INVENTORY_DATE,
        ONHAND_QTY::NUMBER                  AS ONHAND_QTY,
        INTRANSIT_QTY::NUMBER               AS INTRANSIT_QTY,
        ONORDER_QTY::NUMBER                 AS ONORDER_QTY,
        RECEIPTS_QTY::NUMBER                AS RECEIPTS_QTY,
        DROP_SHIP_QTY::NUMBER               AS DROP_SHIP_QTY,
        _SOURCE_FILE, _LOADED_AT,
        CURRENT_TIMESTAMP()                 AS _STAGED_AT,
        CASE WHEN SKU_ID IS NULL THEN 'FAIL' ELSE 'PASS' END         AS DQ_SKU_ID,
        CASE WHEN STORE_ID IS NULL THEN 'FAIL' ELSE 'PASS' END       AS DQ_STORE_ID,
        CASE WHEN INVENTORY_DATE IS NULL THEN 'FAIL' ELSE 'PASS' END AS DQ_INVENTORY_DATE,
        CASE WHEN ONHAND_QTY::NUMBER < 0 THEN 'FAIL' ELSE 'PASS' END AS DQ_ONHAND_QTY
    FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY CHANNEL_ID, SKU_ID, STORE_ID, INVENTORY_DATE ORDER BY _LOADED_AT DESC) AS RN
        FROM DB_TEAM1.BRONZE.INVENTORY
    ) WHERE RN = 1;

    -- silver product
    CREATE OR REPLACE TABLE DB_TEAM1.SILVER.PRODUCT AS
    SELECT
        DIVISION_CODE, DIVISION_DESC, DEPARTMENT_CODE, DEPARTMENT_DESC,
        CLASS_CODE, CLASS_DESC, SUBCLASS_CODE, SUBCLASS_DESC,
        VENDOR_ID, VENDOR_NAME, STYLE_ID, STYLE_DESC, COLOR_ID,
        COLOR_DESC, COLOR_FAMILY_DESC, SIZE, SKU_ID, PRODUCT_STATUS,
        UNIT_RETAIL_PRICE::FLOAT AS UNIT_RETAIL_PRICE,
        UNIT_LAUNCH_PRICE::FLOAT AS UNIT_LAUNCH_PRICE,
        CURRENT_MSRP::FLOAT      AS CURRENT_MSRP,
        UNIT_COST::FLOAT         AS UNIT_COST,
        TRY_TO_DATE(LAUNCH_DATE::STRING) AS LAUNCH_DATE,
        SEASON_CODE, SEASON_CODE_DESC, FASHION_GRADE, EAN,
        CARRYOVER, COLLECTION, PRICE_STATUS,
        TRY_TO_DATE(EXIT_DATE::STRING) AS EXIT_DATE,
        BRAND, MATERIAL, PRODUCT_LIFE_CYCLE,
        TRY_TO_TIMESTAMP(REPLACE(CREATED_TIMESTAMP, '-', ' '), 'YYYY MM DD HH24.MI.SS.FF6') AS CREATED_TIMESTAMP,
        TRY_TO_TIMESTAMP(REPLACE(UPDATED_TIMESTAMP, '-', ' '), 'YYYY MM DD HH24.MI.SS.FF6') AS UPDATED_TIMESTAMP,
        _SOURCE_FILE, _LOADED_AT,
        CURRENT_TIMESTAMP()      AS _STAGED_AT,
        CASE WHEN SKU_ID IS NULL THEN 'FAIL' ELSE 'PASS' END             AS DQ_SKU_ID,
        CASE WHEN PRODUCT_STATUS IS NULL THEN 'FAIL' ELSE 'PASS' END     AS DQ_PRODUCT_STATUS,
        CASE WHEN UNIT_RETAIL_PRICE IS NULL OR UNIT_RETAIL_PRICE::FLOAT < 0 THEN 'FAIL' ELSE 'PASS' END AS DQ_PRICE
    FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY SKU_ID ORDER BY _LOADED_AT DESC) AS RN
        FROM DB_TEAM1.BRONZE.PRODUCT
    ) WHERE RN = 1;

    -- silver store
    CREATE OR REPLACE TABLE DB_TEAM1.SILVER.STORE AS
    SELECT
        CHANNEL_DESC, CHANNEL_ID,
        STORE_ID::NUMBER                        AS STORE_ID,
        STORE_NAME, STORE_STATUS,
        TRY_TO_DATE(STORE_OPEN_DATE::STRING)    AS STORE_OPEN_DATE,
        TRY_TO_DATE(STORE_CLOSE_DATE::STRING)   AS STORE_CLOSE_DATE,
        STORE_TYPE,
        LONGITUDE::FLOAT AS LONGITUDE, LATITUDE::FLOAT AS LATITUDE,
        COUNTRY, DISTRICT, REGION, CITY, STATE, ZIPCODE,
        LOCATION_TYPE, CLIMATE,
        TOTAL_STORE_AREA::NUMBER   AS TOTAL_STORE_AREA,
        STORE_SELLING_AREA::NUMBER AS STORE_SELLING_AREA,
        TRAFFIC::NUMBER            AS TRAFFIC,
        LIKE_STORE_ID, STORE_TIER_GRADE,
        TRY_TO_DATE(COMP_DATE::STRING) AS COMP_DATE,
        COMP_STATUS, PERIMETER,
        TRY_TO_TIMESTAMP(REPLACE(CREATED_TIMESTAMP, '-', ' '), 'YYYY MM DD HH24.MI.SS.FF6') AS CREATED_TIMESTAMP,
        TRY_TO_TIMESTAMP(REPLACE(UPDATED_TIMESTAMP, '-', ' '), 'YYYY MM DD HH24.MI.SS.FF6') AS UPDATED_TIMESTAMP,
        _SOURCE_FILE, _LOADED_AT,
        CURRENT_TIMESTAMP()        AS _STAGED_AT,
        CASE WHEN STORE_ID IS NULL THEN 'FAIL' ELSE 'PASS' END       AS DQ_STORE_ID,
        CASE WHEN STORE_NAME IS NULL THEN 'FAIL' ELSE 'PASS' END     AS DQ_STORE_NAME,
        CASE WHEN STORE_STATUS IS NULL THEN 'FAIL' ELSE 'PASS' END   AS DQ_STORE_STATUS,
        CASE WHEN STORE_OPEN_DATE IS NULL THEN 'FAIL' ELSE 'PASS' END AS DQ_OPEN_DATE
    FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY STORE_ID ORDER BY _LOADED_AT DESC) AS RN
        FROM DB_TEAM1.BRONZE.STORE
    ) WHERE RN = 1;

    -- gold 1: daily sales summary
    CREATE OR REPLACE TABLE DB_TEAM1.GOLD.DAILY_SALES_SUMMARY AS
    SELECT
        T.TRANSACTION_DATE,
        T.STORE_ID_ORIGIN                               AS STORE_ID,
        S.STORE_NAME, S.CITY, S.REGION, S.COUNTRY, S.STORE_TYPE,
        COUNT(DISTINCT T.TRANSACTION_ID)                AS TOTAL_TRANSACTIONS,
        SUM(T.QUANTITY_SOLD)                            AS TOTAL_UNITS_SOLD,
        SUM(T.TOTAL_EXTENDED_LINE_AMOUNT)               AS TOTAL_REVENUE,
        SUM(T.TOTAL_COST)                               AS TOTAL_COST,
        SUM(T.TOTAL_EXTENDED_LINE_AMOUNT) - SUM(T.TOTAL_COST) AS GROSS_PROFIT,
        SUM(T.DISCOUNT_AMOUNT)                          AS TOTAL_DISCOUNT,
        AVG(T.UNIT_NET_SELLING_PRICE)                   AS AVG_SELLING_PRICE
    FROM DB_TEAM1.SILVER.TRANSACTIONS T
    LEFT JOIN DB_TEAM1.SILVER.STORE S
        ON LPAD(T.STORE_ID_ORIGIN, 3, '0') = LPAD(S.STORE_ID::STRING, 3, '0')
    WHERE T.DQ_TRANSACTION_ID = 'PASS'
      AND T.DQ_QUANTITY       = 'PASS'
      AND T.DQ_AMOUNT         = 'PASS'
    GROUP BY 1, 2, 3, 4, 5, 6, 7;

    -- gold 2: product sales performance
    CREATE OR REPLACE TABLE DB_TEAM1.GOLD.PRODUCT_SALES_PERFORMANCE AS
    SELECT
        T.TRANSACTION_DATE, T.SKU_ID,
        P.STYLE_DESC, P.DIVISION_DESC, P.DEPARTMENT_DESC,
        P.CLASS_DESC, P.BRAND, P.PRODUCT_STATUS, P.COLOR_DESC, P.SIZE,
        COUNT(DISTINCT T.TRANSACTION_ID)                AS TOTAL_TRANSACTIONS,
        SUM(T.QUANTITY_SOLD)                            AS TOTAL_UNITS_SOLD,
        SUM(T.TOTAL_EXTENDED_LINE_AMOUNT)               AS TOTAL_REVENUE,
        SUM(T.TOTAL_COST)                               AS TOTAL_COST,
        SUM(T.TOTAL_EXTENDED_LINE_AMOUNT) - SUM(T.TOTAL_COST) AS GROSS_PROFIT,
        SUM(T.DISCOUNT_AMOUNT)                          AS TOTAL_DISCOUNT,
        AVG(T.DISCOUNT_AMOUNT)                          AS AVG_DISCOUNT
    FROM DB_TEAM1.SILVER.TRANSACTIONS T
    LEFT JOIN DB_TEAM1.SILVER.PRODUCT P ON T.SKU_ID = P.SKU_ID
    WHERE T.DQ_TRANSACTION_ID = 'PASS'
      AND T.DQ_QUANTITY       = 'PASS'
    GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10;

    -- gold 3: inventory health
    CREATE OR REPLACE TABLE DB_TEAM1.GOLD.INVENTORY_HEALTH AS
    SELECT
        I.INVENTORY_DATE, I.STORE_ID,
        S.STORE_NAME, S.CITY, S.REGION, S.COUNTRY,
        I.SKU_ID, P.STYLE_DESC, P.DIVISION_DESC, P.DEPARTMENT_DESC, P.BRAND,
        I.CHANNEL_ID, I.CHANNEL_DESC,
        I.ONHAND_QTY, I.INTRANSIT_QTY, I.ONORDER_QTY,
        I.RECEIPTS_QTY, I.DROP_SHIP_QTY,
        I.ONHAND_QTY + I.INTRANSIT_QTY + I.ONORDER_QTY AS TOTAL_AVAILABLE_QTY,
        CASE
            WHEN I.ONHAND_QTY = 0 THEN 'OUT OF STOCK'
            WHEN I.ONHAND_QTY < 5 THEN 'LOW STOCK'
            ELSE                       'IN STOCK'
        END AS STOCK_STATUS
    FROM DB_TEAM1.SILVER.INVENTORY I
    LEFT JOIN DB_TEAM1.SILVER.STORE   S ON I.STORE_ID = S.STORE_ID
    LEFT JOIN DB_TEAM1.SILVER.PRODUCT P ON I.SKU_ID   = P.SKU_ID
    WHERE I.DQ_SKU_ID   = 'PASS'
      AND I.DQ_STORE_ID = 'PASS';

END;

-- wire email task after this new task instead of directly after fallback
ALTER TASK DB_TEAM1.BRONZE.TASK_SEND_FAILURE_EMAIL SUSPEND;

CREATE OR REPLACE TASK DB_TEAM1.BRONZE.TASK_SEND_FAILURE_EMAIL
    WAREHOUSE = SNOWFLAKE_LEARNING_WH
    COMMENT   = 'Sends email if both primary and fallback runs failed today'
    AFTER DB_TEAM1.BRONZE.TASK_FALLBACK_SILVER_GOLD_REFRESH
AS
DECLARE
    v_any_success INTEGER DEFAULT 0;
    v_error_summary STRING DEFAULT '';
BEGIN
    SELECT COUNT(*) INTO :v_any_success
    FROM DB_TEAM1.BRONZE.PIPELINE_LOG
    WHERE STATUS = 'SUCCESS'
      AND DATE(RUN_TIMESTAMP) = CURRENT_DATE();

    IF (:v_any_success > 0) THEN
        RETURN 'A run succeeded today, no alert needed';
    END IF;

    SELECT LISTAGG(
        'Run type: ' || RUN_TYPE ||
        ' | Status: ' || STATUS ||
        ' | Error: ' || COALESCE(ERROR_MESSAGE, 'No new files found in GCS') ||
        ' | Time: ' || RUN_TIMESTAMP::STRING,
        CHAR(10)
    ) INTO :v_error_summary
    FROM DB_TEAM1.BRONZE.PIPELINE_LOG
    WHERE DATE(RUN_TIMESTAMP) = CURRENT_DATE();

    CALL SYSTEM$SEND_EMAIL(
        'EMAIL_NOTIFICATIONS_TEAM1',
        'name@comapnyid.co,name@comapnyid.co,
        'S&S Retail Pipeline FAILED - ' || CURRENT_DATE()::STRING,
        'Both the 12:30pm IST primary run and the 4:00pm IST fallback run failed to load new data today.' ||
        CHAR(10) || CHAR(10) ||
        'Details from DB_TEAM1.BRONZE.PIPELINE_LOG:' ||
        CHAR(10) || CHAR(10) ||
        :v_error_summary ||
        CHAR(10) || CHAR(10) ||
        'Please check the GCS bucket data-integration-scrape for missing files, ' ||
        'or query the PIPELINE_LOG table directly for full error details.'
    );
END;

-- resume everything in correct order
ALTER TASK DB_TEAM1.BRONZE.TASK_SEND_FAILURE_EMAIL              RESUME;
ALTER TASK DB_TEAM1.BRONZE.TASK_FALLBACK_SILVER_GOLD_REFRESH    RESUME;
ALTER TASK DB_TEAM1.BRONZE.TASK_FALLBACK_BRONZE_LOAD            RESUME;

-- verify full graph
SHOW TASKS IN SCHEMA DB_TEAM1.BRONZE;