-- ============================================================
-- FILE NAME: bronze.sql
-- FILE 03: BRONZE LOAD — COPY INTO ALL 4 TABLES
-- Project : S&S Retail — End-to-End Snowflake Pipeline
-- Run this THIRD, after stage_creation.sql
-- Transactions & Inventory : TRUNCATE + COPY (incremental)
-- Product & Store          : TRUNCATE + COPY (full refresh)
-- CHANGE: Patterns fixed to match historic_data folder structure
--         Stage now points to root so patterns must be specific
-- ============================================================

USE ROLE SNOWFLAKE_LEARNING_ROLE;
USE DATABASE DB_TEAM1;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE SCHEMA DB_TEAM1.BRONZE;

-- ============================================================
-- TRANSACTIONS — TRUNCATE + COPY
-- ============================================================

TRUNCATE TABLE DB_TEAM1.BRONZE.TRANSACTIONS;

COPY INTO DB_TEAM1.BRONZE.TRANSACTIONS (
    CHANNEL_ID, CHANNEL_DESC, TRANSACTION_ID, TRANSACTION_DATE,
    TRANSACTION_TYPE, LINE_ID, SKU_ID, STORE_ID_ORIGIN,
    STORE_ID_FULLFILLED, ORDER_FULFILLMENT_METHOD, QUANTITY_SOLD,
    CURRENT_MSRP, UNIT_RETAIL_PRICE, DISCOUNT_AMOUNT,
    UNIT_NET_SELLING_PRICE, TOTAL_EXTENDED_LINE_AMOUNT,
    UNIT_COST, TOTAL_COST, PRICE_STATUS, CLEARANCE_INDICATOR,
    LAUNCH_DATE, LAUNCH_PRICE, CREATED_TIMESTAMP, UPDATED_TIMESTAMP,
    _SOURCE_FILE
)
FROM (
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
        $21, $22, $23, $24,
        METADATA$FILENAME
    FROM @DB_TEAM1.BRONZE.GCS_RAW_STAGE
)
PATTERN = '.*historic_data/[0-9]{4}-[0-9]{2}-[0-9]{2}/Transactions_[0-9]+\.csv'
FILE_FORMAT = (
    TYPE                         = 'CSV'
    FIELD_DELIMITER              = '|'
    SKIP_HEADER                  = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF                      = ('', 'NULL', 'null')
    EMPTY_FIELD_AS_NULL          = TRUE
)
FORCE = TRUE
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) AS TRANSACTIONS_LOADED FROM DB_TEAM1.BRONZE.TRANSACTIONS;

-- ============================================================
-- INVENTORY — TRUNCATE + COPY
-- ============================================================

TRUNCATE TABLE DB_TEAM1.BRONZE.INVENTORY;

COPY INTO DB_TEAM1.BRONZE.INVENTORY (
    CHANNEL_ID, CHANNEL_DESC, SKU_ID, STORE_ID, INVENTORY_DATE,
    ONHAND_QTY, INTRANSIT_QTY, ONORDER_QTY, RECEIPTS_QTY,
    DROP_SHIP_QTY, _SOURCE_FILE
)
FROM (
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        METADATA$FILENAME
    FROM @DB_TEAM1.BRONZE.GCS_RAW_STAGE
)
PATTERN = '.*historic_data/[0-9]{4}-[0-9]{2}-[0-9]{2}/Inventory_[0-9]+\.csv'
FILE_FORMAT = (
    TYPE                         = 'CSV'
    FIELD_DELIMITER              = '|'
    SKIP_HEADER                  = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF                      = ('', 'NULL', 'null')
    EMPTY_FIELD_AS_NULL          = TRUE
)
FORCE = TRUE
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) AS INVENTORY_LOADED FROM DB_TEAM1.BRONZE.INVENTORY;

-- ============================================================
-- PRODUCT — TRUNCATE + COPY (full refresh)
-- ============================================================

TRUNCATE TABLE DB_TEAM1.BRONZE.PRODUCT;

COPY INTO DB_TEAM1.BRONZE.PRODUCT (
    DIVISION_CODE, DIVISION_DESC, DEPARTMENT_CODE, DEPARTMENT_DESC,
    CLASS_CODE, CLASS_DESC, SUBCLASS_CODE, SUBCLASS_DESC,
    VENDOR_ID, VENDOR_NAME, STYLE_ID, STYLE_DESC, COLOR_ID,
    COLOR_DESC, COLOR_FAMILY_DESC, SIZE, SKU_ID, PRODUCT_STATUS,
    UNIT_RETAIL_PRICE, UNIT_LAUNCH_PRICE, CURRENT_MSRP, UNIT_COST,
    LAUNCH_DATE, SEASON_CODE, SEASON_CODE_DESC, FASHION_GRADE,
    EAN, CARRYOVER, COLLECTION, PRICE_STATUS, EXIT_DATE,
    BRAND, MATERIAL, PRODUCT_LIFE_CYCLE,
    CREATED_TIMESTAMP, UPDATED_TIMESTAMP, _SOURCE_FILE
)
FROM (
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
        $21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
        $31, $32, $33, $34, $35, $36,
        METADATA$FILENAME
    FROM @DB_TEAM1.BRONZE.GCS_RAW_STAGE
)
PATTERN = '.*historic_data/[0-9]{4}-[0-9]{2}-[0-9]{2}/Product_[0-9]+\.csv'
FILE_FORMAT = (
    TYPE                         = 'CSV'
    FIELD_DELIMITER              = '|'
    SKIP_HEADER                  = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF                      = ('', 'NULL', 'null')
    EMPTY_FIELD_AS_NULL          = TRUE
)
FORCE = TRUE
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) AS PRODUCT_LOADED FROM DB_TEAM1.BRONZE.PRODUCT;

-- ============================================================
-- STORE — TRUNCATE + COPY (full refresh)
-- ============================================================

TRUNCATE TABLE DB_TEAM1.BRONZE.STORE;

COPY INTO DB_TEAM1.BRONZE.STORE (
    CHANNEL_DESC, CHANNEL_ID, STORE_ID, STORE_NAME, STORE_STATUS,
    STORE_OPEN_DATE, STORE_CLOSE_DATE, STORE_TYPE, LONGITUDE, LATITUDE,
    COUNTRY, DISTRICT, REGION, CITY, STATE, ZIPCODE,
    LOCATION_TYPE, CLIMATE, TOTAL_STORE_AREA, STORE_SELLING_AREA,
    TRAFFIC, LIKE_STORE_ID, STORE_TIER_GRADE, COMP_DATE,
    COMP_STATUS, PERIMETER, CREATED_TIMESTAMP, UPDATED_TIMESTAMP,
    _SOURCE_FILE
)
FROM (
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
        $21, $22, $23, $24, $25, $26, $27, $28,
        METADATA$FILENAME
    FROM @DB_TEAM1.BRONZE.GCS_RAW_STAGE
)
PATTERN = '.*historic_data/[0-9]{4}-[0-9]{2}-[0-9]{2}/Store_[0-9]+\.csv'
FILE_FORMAT = (
    TYPE                         = 'CSV'
    FIELD_DELIMITER              = '|'
    SKIP_HEADER                  = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF                      = ('', 'NULL', 'null')
    EMPTY_FIELD_AS_NULL          = TRUE
)
FORCE = TRUE
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) AS STORE_LOADED FROM DB_TEAM1.BRONZE.STORE;

-- ============================================================
-- VERIFY ALL 4 TABLES
-- ============================================================
SELECT 'TRANSACTIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DB_TEAM1.BRONZE.TRANSACTIONS
UNION ALL
SELECT 'INVENTORY',                   COUNT(*) FROM DB_TEAM1.BRONZE.INVENTORY
UNION ALL
SELECT 'PRODUCT',                     COUNT(*) FROM DB_TEAM1.BRONZE.PRODUCT
UNION ALL
SELECT 'STORE',                       COUNT(*) FROM DB_TEAM1.BRONZE.STORE;


USE ROLE SNOWFLAKE_LEARNING_ROLE;
USE DATABASE DB_TEAM1;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- silver transactions
CREATE OR REPLACE TABLE DB_TEAM1.SILVER.TRANSACTIONS AS
SELECT
    CHANNEL_ID, CHANNEL_DESC, TRANSACTION_ID,
    TRY_TO_DATE(TRANSACTION_DATE::STRING)           AS TRANSACTION_DATE,
    TRANSACTION_TYPE,
    LINE_ID::NUMBER                                 AS LINE_ID,
    SKU_ID, STORE_ID_ORIGIN, STORE_ID_FULLFILLED,
    ORDER_FULFILLMENT_METHOD,
    QUANTITY_SOLD::NUMBER                           AS QUANTITY_SOLD,
    CURRENT_MSRP::FLOAT                             AS CURRENT_MSRP,
    UNIT_RETAIL_PRICE::FLOAT                        AS UNIT_RETAIL_PRICE,
    DISCOUNT_AMOUNT::FLOAT                          AS DISCOUNT_AMOUNT,
    UNIT_NET_SELLING_PRICE::FLOAT                   AS UNIT_NET_SELLING_PRICE,
    TOTAL_EXTENDED_LINE_AMOUNT::FLOAT               AS TOTAL_EXTENDED_LINE_AMOUNT,
    UNIT_COST::FLOAT                                AS UNIT_COST,
    TOTAL_COST::FLOAT                               AS TOTAL_COST,
    PRICE_STATUS, CLEARANCE_INDICATOR,
    TRY_TO_DATE(LAUNCH_DATE::STRING)                AS LAUNCH_DATE,
    LAUNCH_PRICE::FLOAT                             AS LAUNCH_PRICE,
    TRY_TO_TIMESTAMP(
        REPLACE(CREATED_TIMESTAMP, '-', ' '),
        'YYYY MM DD HH24.MI.SS.FF6'
    )                                               AS CREATED_TIMESTAMP,
    TRY_TO_TIMESTAMP(
        REPLACE(UPDATED_TIMESTAMP, '-', ' '),
        'YYYY MM DD HH24.MI.SS.FF6'
    )                                               AS UPDATED_TIMESTAMP,
    _SOURCE_FILE, _LOADED_AT,
    CURRENT_TIMESTAMP()                             AS _STAGED_AT,
    CASE WHEN TRANSACTION_ID IS NULL
        THEN 'FAIL' ELSE 'PASS' END                 AS DQ_TRANSACTION_ID,
    CASE WHEN SKU_ID IS NULL
        THEN 'FAIL' ELSE 'PASS' END                 AS DQ_SKU_ID,
    CASE WHEN STORE_ID_ORIGIN IS NULL
        THEN 'FAIL' ELSE 'PASS' END                 AS DQ_STORE_ID,
    CASE WHEN QUANTITY_SOLD IS NULL OR QUANTITY_SOLD::NUMBER < 0
        THEN 'FAIL' ELSE 'PASS' END                 AS DQ_QUANTITY,
    CASE WHEN TOTAL_EXTENDED_LINE_AMOUNT IS NULL
         OR TOTAL_EXTENDED_LINE_AMOUNT::FLOAT < 0
        THEN 'FAIL' ELSE 'PASS' END                 AS DQ_AMOUNT
FROM (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY TRANSACTION_ID, LINE_ID
            ORDER BY _LOADED_AT DESC
        ) AS RN
    FROM DB_TEAM1.BRONZE.TRANSACTIONS
)
WHERE RN = 1;

-- silver inventory
CREATE OR REPLACE TABLE DB_TEAM1.SILVER.INVENTORY AS
SELECT
    CHANNEL_ID, CHANNEL_DESC, SKU_ID,
    STORE_ID::NUMBER                    AS STORE_ID,
    TRY_TO_DATE(INVENTORY_DATE::STRING) AS INVENTORY_DATE,
    ONHAND_QTY::NUMBER                  AS ONHAND_QTY,
    INTRANSIT_QTY::NUMBER               AS INTRANSIT_QTY,
    ONORDER_QTY::NUMBER                 AS ONORDER_QTY,
    RECEIPTS_QTY::NUMBER                AS RECEIPTS_QTY,
    DROP_SHIP_QTY::NUMBER               AS DROP_SHIP_QTY,
    _SOURCE_FILE, _LOADED_AT,
    CURRENT_TIMESTAMP()                 AS _STAGED_AT,
    CASE WHEN SKU_ID IS NULL
        THEN 'FAIL' ELSE 'PASS' END     AS DQ_SKU_ID,
    CASE WHEN STORE_ID IS NULL
        THEN 'FAIL' ELSE 'PASS' END     AS DQ_STORE_ID,
    CASE WHEN INVENTORY_DATE IS NULL
        THEN 'FAIL' ELSE 'PASS' END     AS DQ_INVENTORY_DATE,
    CASE WHEN ONHAND_QTY::NUMBER < 0
        THEN 'FAIL' ELSE 'PASS' END     AS DQ_ONHAND_QTY
FROM (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY CHANNEL_ID, SKU_ID, STORE_ID, INVENTORY_DATE
            ORDER BY _LOADED_AT DESC
        ) AS RN
    FROM DB_TEAM1.BRONZE.INVENTORY
)
WHERE RN = 1;

-- silver product
CREATE OR REPLACE TABLE DB_TEAM1.SILVER.PRODUCT AS
SELECT
    DIVISION_CODE, DIVISION_DESC, DEPARTMENT_CODE, DEPARTMENT_DESC,
    CLASS_CODE, CLASS_DESC, SUBCLASS_CODE, SUBCLASS_DESC,
    VENDOR_ID, VENDOR_NAME, STYLE_ID, STYLE_DESC, COLOR_ID,
    COLOR_DESC, COLOR_FAMILY_DESC, SIZE, SKU_ID, PRODUCT_STATUS,
    UNIT_RETAIL_PRICE::FLOAT            AS UNIT_RETAIL_PRICE,
    UNIT_LAUNCH_PRICE::FLOAT            AS UNIT_LAUNCH_PRICE,
    CURRENT_MSRP::FLOAT                 AS CURRENT_MSRP,
    UNIT_COST::FLOAT                    AS UNIT_COST,
    TRY_TO_DATE(LAUNCH_DATE::STRING)    AS LAUNCH_DATE,
    SEASON_CODE, SEASON_CODE_DESC, FASHION_GRADE, EAN,
    CARRYOVER, COLLECTION, PRICE_STATUS,
    TRY_TO_DATE(EXIT_DATE::STRING)      AS EXIT_DATE,
    BRAND, MATERIAL, PRODUCT_LIFE_CYCLE,
    TRY_TO_TIMESTAMP(
        REPLACE(CREATED_TIMESTAMP, '-', ' '),
        'YYYY MM DD HH24.MI.SS.FF6'
    )                                   AS CREATED_TIMESTAMP,
    TRY_TO_TIMESTAMP(
        REPLACE(UPDATED_TIMESTAMP, '-', ' '),
        'YYYY MM DD HH24.MI.SS.FF6'
    )                                   AS UPDATED_TIMESTAMP,
    _SOURCE_FILE, _LOADED_AT,
    CURRENT_TIMESTAMP()                 AS _STAGED_AT,
    CASE WHEN SKU_ID IS NULL
        THEN 'FAIL' ELSE 'PASS' END     AS DQ_SKU_ID,
    CASE WHEN PRODUCT_STATUS IS NULL
        THEN 'FAIL' ELSE 'PASS' END     AS DQ_PRODUCT_STATUS,
    CASE WHEN UNIT_RETAIL_PRICE IS NULL OR UNIT_RETAIL_PRICE::FLOAT < 0
        THEN 'FAIL' ELSE 'PASS' END     AS DQ_PRICE
FROM (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY SKU_ID
            ORDER BY _LOADED_AT DESC
        ) AS RN
    FROM DB_TEAM1.BRONZE.PRODUCT
)
WHERE RN = 1;

-- silver store
CREATE OR REPLACE TABLE DB_TEAM1.SILVER.STORE AS
SELECT
    CHANNEL_DESC, CHANNEL_ID,
    STORE_ID::NUMBER                        AS STORE_ID,
    STORE_NAME, STORE_STATUS,
    TRY_TO_DATE(STORE_OPEN_DATE::STRING)    AS STORE_OPEN_DATE,
    TRY_TO_DATE(STORE_CLOSE_DATE::STRING)   AS STORE_CLOSE_DATE,
    STORE_TYPE,
    LONGITUDE::FLOAT                        AS LONGITUDE,
    LATITUDE::FLOAT                         AS LATITUDE,
    COUNTRY, DISTRICT, REGION, CITY, STATE, ZIPCODE,
    LOCATION_TYPE, CLIMATE,
    TOTAL_STORE_AREA::NUMBER                AS TOTAL_STORE_AREA,
    STORE_SELLING_AREA::NUMBER              AS STORE_SELLING_AREA,
    TRAFFIC::NUMBER                         AS TRAFFIC,
    LIKE_STORE_ID, STORE_TIER_GRADE,
    TRY_TO_DATE(COMP_DATE::STRING)          AS COMP_DATE,
    COMP_STATUS, PERIMETER,
    TRY_TO_TIMESTAMP(
        REPLACE(CREATED_TIMESTAMP, '-', ' '),
        'YYYY MM DD HH24.MI.SS.FF6'
    )                                       AS CREATED_TIMESTAMP,
    TRY_TO_TIMESTAMP(
        REPLACE(UPDATED_TIMESTAMP, '-', ' '),
        'YYYY MM DD HH24.MI.SS.FF6'
    )                                       AS UPDATED_TIMESTAMP,
    _SOURCE_FILE, _LOADED_AT,
    CURRENT_TIMESTAMP()